// Generated by gencpp from file onrobot_vg_control/SetCommand.msg
// DO NOT EDIT!


#ifndef ONROBOT_VG_CONTROL_MESSAGE_SETCOMMAND_H
#define ONROBOT_VG_CONTROL_MESSAGE_SETCOMMAND_H

#include <ros/service_traits.h>


#include <onrobot_vg_control/SetCommandRequest.h>
#include <onrobot_vg_control/SetCommandResponse.h>


namespace onrobot_vg_control
{

struct SetCommand
{

typedef SetCommandRequest Request;
typedef SetCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCommand
} // namespace onrobot_vg_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::onrobot_vg_control::SetCommand > {
  static const char* value()
  {
    return "c348f8d8cd3a80f54328aa4159009109";
  }

  static const char* value(const ::onrobot_vg_control::SetCommand&) { return value(); }
};

template<>
struct DataType< ::onrobot_vg_control::SetCommand > {
  static const char* value()
  {
    return "onrobot_vg_control/SetCommand";
  }

  static const char* value(const ::onrobot_vg_control::SetCommand&) { return value(); }
};


// service_traits::MD5Sum< ::onrobot_vg_control::SetCommandRequest> should match
// service_traits::MD5Sum< ::onrobot_vg_control::SetCommand >
template<>
struct MD5Sum< ::onrobot_vg_control::SetCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::onrobot_vg_control::SetCommand >::value();
  }
  static const char* value(const ::onrobot_vg_control::SetCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::onrobot_vg_control::SetCommandRequest> should match
// service_traits::DataType< ::onrobot_vg_control::SetCommand >
template<>
struct DataType< ::onrobot_vg_control::SetCommandRequest>
{
  static const char* value()
  {
    return DataType< ::onrobot_vg_control::SetCommand >::value();
  }
  static const char* value(const ::onrobot_vg_control::SetCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::onrobot_vg_control::SetCommandResponse> should match
// service_traits::MD5Sum< ::onrobot_vg_control::SetCommand >
template<>
struct MD5Sum< ::onrobot_vg_control::SetCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::onrobot_vg_control::SetCommand >::value();
  }
  static const char* value(const ::onrobot_vg_control::SetCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::onrobot_vg_control::SetCommandResponse> should match
// service_traits::DataType< ::onrobot_vg_control::SetCommand >
template<>
struct DataType< ::onrobot_vg_control::SetCommandResponse>
{
  static const char* value()
  {
    return DataType< ::onrobot_vg_control::SetCommand >::value();
  }
  static const char* value(const ::onrobot_vg_control::SetCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ONROBOT_VG_CONTROL_MESSAGE_SETCOMMAND_H
